import type { BrokerConfig } from "@/types/database";

const CALLBACK_PATH = "/api/broker/oauth/callback";

export const BROKERS: BrokerConfig[] = [
  {
    id: "upstox",
    name: "Upstox",
    logo: "\uD83D\uDCC8",
    color: "violet",
    authType: "oauth",
    website: "https://upstox.com",
    apiDocsUrl: "https://upstox.com/developer/api-documentation",
    description: "Modern trading platform with powerful APIs",
    redirectUri: (process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000") + CALLBACK_PATH,
    fields: [
      {
        key: "api_key",
        label: "API Key",
        type: "text",
        placeholder: "Enter your Upstox API Key",
        helpText: "Found in Upstox Developer Console",
      },
      {
        key: "api_secret",
        label: "API Secret",
        type: "password",
        placeholder: "Enter your Upstox API Secret",
        helpText: "Keep this secret and never share",
      },
      {
        key: "access_token",
        label: "Access Token",
        type: "password",
        placeholder: "Enter your Access Token",
        helpText: "Generated after OAuth authorization",
      },
    ],
    setupSteps: [
      "Go to Upstox Developer Console",
      "Create a new app and get API Key & Secret",
      "Generate Access Token via OAuth flow",
      "Paste credentials here to connect",
    ],
  },
  {
    id: "angelone",
    name: "AngelOne",
    logo: "\uD83D\uDC7C",
    color: "orange",
    authType: "apikey",
    website: "https://www.angelone.in",
    apiDocsUrl: "https://smartapi.angelbroking.com/docs",
    description: "Full-service broker with SmartAPI",
    fields: [
      {
        key: "api_key",
        label: "API Key",
        type: "text",
        placeholder: "Enter your SmartAPI Key",
        helpText: "Found in SmartAPI Dashboard",
      },
      {
        key: "client_id",
        label: "Client ID",
        type: "text",
        placeholder: "Enter your Client ID",
        helpText: "Your AngelOne Client/User ID",
      },
      {
        key: "totp_secret",
        label: "TOTP Secret",
        type: "password",
        placeholder: "Enter your TOTP Secret Key",
        helpText: "Used for 2FA authentication",
      },
    ],
    setupSteps: [
      "Login to AngelOne SmartAPI portal",
      "Create a new app to get API Key",
      "Note your Client ID from profile",
      "Enable TOTP and save the secret key",
      "Paste all credentials here to connect",
    ],
  },
  {
    id: "zerodha",
    name: "Zerodha",
    logo: "\uD83D\uDD35",
    color: "blue",
    authType: "oauth",
    website: "https://zerodha.com",
    apiDocsUrl: "https://kite.trade/docs/connect/v3",
    description: "India largest stockbroker with Kite Connect API",
    redirectUri: (process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000") + CALLBACK_PATH,
    fields: [
      {
        key: "api_key",
        label: "API Key",
        type: "text",
        placeholder: "Enter your Kite API Key",
        helpText: "Found in Kite Connect Developer Console",
      },
      {
        key: "api_secret",
        label: "API Secret",
        type: "password",
        placeholder: "Enter your API Secret",
        helpText: "Keep this secret and never share",
      },
      {
        key: "access_token",
        label: "Access Token",
        type: "password",
        placeholder: "Enter your Access Token",
        helpText: "Generated daily via OAuth login",
      },
    ],
    setupSteps: [
      "Go to Kite Connect Developer Console",
      "Create an app and get API Key & Secret",
      "Generate daily Access Token via login URL",
      "Paste credentials here to connect",
    ],
  },
  {
    id: "dhan",
    name: "Dhan",
    logo: "\uD83D\uDC8E",
    color: "cyan",
    authType: "token",
    website: "https://dhan.co",
    apiDocsUrl: "https://dhanhq.co/docs/latest",
    description: "New age trading platform with DhanHQ API",
    fields: [
      {
        key: "client_id",
        label: "Client ID",
        type: "text",
        placeholder: "Enter your Dhan Client ID",
        helpText: "Your Dhan account Client ID",
      },
      {
        key: "access_token",
        label: "Access Token",
        type: "password",
        placeholder: "Enter your Access Token",
        helpText: "Generated from Dhan developer portal",
      },
    ],
    setupSteps: [
      "Login to Dhan developer portal",
      "Create an app to get credentials",
      "Copy your Client ID from profile",
      "Generate Access Token from portal",
      "Paste credentials here to connect",
    ],
  },
  {
    id: "groww",
    name: "Groww",
    logo: "\uD83C\uDF31",
    color: "green",
    authType: "token",
    website: "https://groww.in",
    apiDocsUrl: "https://groww.in/developer",
    description: "Popular investment platform with trading API",
    fields: [
      {
        key: "access_token",
        label: "Access Token",
        type: "password",
        placeholder: "Enter your Groww Access Token",
        helpText: "Generated from Groww developer settings",
      },
    ],
    setupSteps: [
      "Login to Groww developer portal",
      "Generate your Access Token",
      "Paste the token here to connect",
    ],
  },
];

export const BROKER_PAGE_CONFIG = {
  title: "Broker Integration",
  subtitle: "Connect your broker to get live market data",
  connectedBadge: "Connected",
  disconnectedBadge: "Disconnected",
  connectButton: "Connect",
  disconnectButton: "Disconnect",
  testButton: "Test Connection",
  saveButton: "Save & Connect",
  rule: "Only 1 broker can be connected at a time",
  securityNote: "Your API credentials are encrypted and stored securely",
  lastConnected: "Last connected",
  setupGuideTitle: "How to get API credentials",
} as const;
